2014/12/02 12:36:32 [error] [exception.CException] exception 'CException' with message 'Alias "ext.cssmenu.CssMenu" is invalid. Make sure it points to an existing PHP file and the file is readable.' in /var/www/html/yii/framework/YiiBase.php:322
Stack trace:
#0 /var/www/html/yii/framework/web/CWidgetFactory.php(146): YiiBase::import('ext.cssmenu.Css...', true)
#1 /var/www/html/yii/framework/web/CBaseController.php(146): CWidgetFactory->createWidget(Object(SiteController), 'ext.cssmenu.Css...', Array)
#2 /var/www/html/yii/framework/web/CBaseController.php(172): CBaseController->createWidget('ext.cssmenu.Css...', Array)
#3 /var/www/html/yii/blog2/protected/views/layouts/main.php(39): CBaseController->widget('ext.cssmenu.Css...', Array)
#4 /var/www/html/yii/framework/web/CBaseController.php(126): require('/var/www/html/y...')
#5 /var/www/html/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/html/y...', Array, true)
#6 /var/www/html/yii/framework/web/widgets/CContentDecorator.php(76): CBaseController->renderFile('/var/www/html/y...', Array, true)
#7 /var/www/html/yii/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#8 /var/www/html/yii/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#9 /var/www/html/yii/framework/web/CBaseController.php(206): COutputProcessor->run()
#10 /var/www/html/yii/framework/web/CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#11 /var/www/html/yii/blog2/protected/views/layouts/column1.php(6): CBaseController->endContent()
#12 /var/www/html/yii/framework/web/CBaseController.php(126): require('/var/www/html/y...')
#13 /var/www/html/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/html/y...', Array, true)
#14 /var/www/html/yii/framework/web/CController.php(784): CBaseController->renderFile('/var/www/html/y...', Array, true)
#15 /var/www/html/yii/blog2/protected/controllers/SiteController.php(32): CController->render('index')
#16 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#17 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#18 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#19 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('')
#21 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#22 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#23 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/yii/blog2/index.php
---
2014/12/02 12:52:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 12:56:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 12:56:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 12:58:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:54:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:54:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:55:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:58:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:58:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:58:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:58:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:58:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:59:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:59:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:59:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:59:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:59:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:59:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:59:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:59:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:59:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 13:59:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 14:01:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 14:01:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 14:01:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 14:01:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 14:01:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 14:01:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 14:01:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 14:01:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "sub1" was not found.' in /var/www/html/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/html/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('sub1')
#1 /var/www/html/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/html/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/blog2/index.php?r=site/page&view=sub1
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=site/login
---
2014/12/02 14:05:08 [error] [php] Undefined index: label (/var/www/html/yii/blog2/protected/extensions/mbmenu/MbMenu.php:172)
Stack trace:
#0 /var/www/html/yii/framework/web/CBaseController.php(147): MbMenu->init()
#1 /var/www/html/yii/framework/web/CBaseController.php(172): SiteController->createWidget()
#2 /var/www/html/yii/blog2/protected/views/layouts/main.php(46): SiteController->widget()
#3 /var/www/html/yii/framework/web/CBaseController.php(126): require()
#4 /var/www/html/yii/framework/web/CBaseController.php(95): SiteController->renderInternal()
#5 /var/www/html/yii/framework/web/widgets/CContentDecorator.php(76): SiteController->renderFile()
#6 /var/www/html/yii/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate()
#7 /var/www/html/yii/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput()
#8 /var/www/html/yii/framework/web/CBaseController.php(206): CContentDecorator->run()
#9 /var/www/html/yii/framework/web/CBaseController.php(300): SiteController->endWidget()
#10 /var/www/html/yii/blog2/protected/views/layouts/column1.php(6): SiteController->endContent()
#11 /var/www/html/yii/framework/web/CBaseController.php(126): require()
#12 /var/www/html/yii/framework/web/CBaseController.php(95): SiteController->renderInternal()
#13 /var/www/html/yii/framework/web/CController.php(784): SiteController->renderFile()
#14 /var/www/html/yii/blog2/protected/controllers/SiteController.php(98): SiteController->render()
#15 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#16 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#17 /var/www/html/yii/framework/web/CController.php(286): SiteController->runAction()
#18 /var/www/html/yii/framework/web/CController.php(265): SiteController->runActionWithFilters()
#19 /var/www/html/yii/framework/web/CWebApplication.php(282): SiteController->run()
#20 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#21 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#22 /var/www/html/yii/blog2/index.php(13): CWebApplication->run()
REQUEST_URI=/yii/blog2/index.php?r=site/login
in /var/www/html/yii/blog2/protected/extensions/mbmenu/MbMenu.php (172)
in /var/www/html/yii/blog2/protected/extensions/mbmenu/MbMenu.php (99)
in /var/www/html/yii/blog2/protected/views/layouts/main.php (46)
2014/12/02 14:21:54 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'test'' in /var/www/html/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/html/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/html/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/html/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=gii/default/index
---
2014/12/02 14:23:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in /var/www/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog2/index.php?r=user/admin
---
2014/12/02 14:23:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "tbluser/admin".' in /var/www/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('tbluser/admin')
#1 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog2/index.php?r=tbluser/admin
---
2014/12/02 14:25:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "tbluser/admin".' in /var/www/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('tbluser/admin')
#1 /var/www/html/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/html/yii/blog2/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog2/index.php?r=tbluser/admin&view=about
HTTP_REFERER=http://localhost/yii/blog2/index.php?r=tblUser/admin
---
2014/12/02 19:06:21 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.tbl_book' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_book`.
in /srv/http/blognew/yii/blog2/index.php (13)
2014/12/02 20:05:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Crear".' in /srv/http/blognew/yii/framework/web/CController.php:483
Stack trace:
#0 /srv/http/blognew/yii/framework/web/CController.php(270): CController->missingAction('Crear')
#1 /srv/http/blognew/yii/framework/web/CWebApplication.php(282): CController->run('Crear')
#2 /srv/http/blognew/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('Book/Crear')
#3 /srv/http/blognew/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /srv/http/blognew/yii/blog2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/blognew/yii/blog2/index.php?r=Book/Crear
---
2014/12/02 20:05:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "crear".' in /srv/http/blognew/yii/framework/web/CController.php:483
Stack trace:
#0 /srv/http/blognew/yii/framework/web/CController.php(270): CController->missingAction('crear')
#1 /srv/http/blognew/yii/framework/web/CWebApplication.php(282): CController->run('crear')
#2 /srv/http/blognew/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('Book/crear')
#3 /srv/http/blognew/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /srv/http/blognew/yii/blog2/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/blognew/yii/blog2/index.php?r=Book/crear
---
2014/12/02 20:08:34 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /srv/http/blognew/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /srv/http/blognew/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /srv/http/blognew/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /srv/http/blognew/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /srv/http/blognew/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /srv/http/blognew/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /srv/http/blognew/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /srv/http/blognew/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /srv/http/blognew/yii/framework/web/CWebApplication.php(282): CController->run('Crear')
#8 /srv/http/blognew/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('tblBook/Crear')
#9 /srv/http/blognew/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /srv/http/blognew/yii/blog2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/blognew/yii/blog2/index.php?r=tblBook/Crear
---
2014/12/02 20:48:13 [error] [php] Undefined variable: model (/srv/http/blognew/yii/blog2/protected/views/tblBook/listar.php:19)
Stack trace:
#0 /srv/http/blognew/yii/framework/web/CController.php(869): TblBookController->renderFile()
#1 /srv/http/blognew/yii/framework/web/CController.php(782): TblBookController->renderPartial()
#2 /srv/http/blognew/yii/blog2/protected/controllers/TblBookController.php(183): TblBookController->render()
#3 /srv/http/blognew/yii/framework/web/actions/CInlineAction.php(49): TblBookController->actionCrear()
#4 /srv/http/blognew/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /srv/http/blognew/yii/framework/web/filters/CFilterChain.php(133): TblBookController->runAction()
#6 /srv/http/blognew/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#7 /srv/http/blognew/yii/framework/web/CController.php(1145): CAccessControlFilter->filter()
#8 /srv/http/blognew/yii/framework/web/filters/CInlineFilter.php(58): TblBookController->filterAccessControl()
#9 /srv/http/blognew/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter()
#10 /srv/http/blognew/yii/framework/web/CController.php(291): CFilterChain->run()
#11 /srv/http/blognew/yii/framework/web/CController.php(265): TblBookController->runActionWithFilters()
#12 /srv/http/blognew/yii/framework/web/CWebApplication.php(282): TblBookController->run()
#13 /srv/http/blognew/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#14 /srv/http/blognew/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /srv/http/blognew/yii/blog2/index.php(13): CWebApplication->run()
REQUEST_URI=/blognew/yii/blog2/index.php?r=tblBook/Crear
in /srv/http/blognew/yii/blog2/protected/views/tblBook/listar.php (19)
in /srv/http/blognew/yii/blog2/protected/controllers/TblBookController.php (183)
in /srv/http/blognew/yii/blog2/index.php (13)
2014/12/03 02:11:39 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /srv/http/blognew/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /srv/http/blognew/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /srv/http/blognew/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /srv/http/blognew/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /srv/http/blognew/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /srv/http/blognew/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /srv/http/blognew/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /srv/http/blognew/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /srv/http/blognew/yii/framework/web/CWebApplication.php(282): CController->run('Crear')
#8 /srv/http/blognew/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('Books/Crear')
#9 /srv/http/blognew/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /srv/http/blognew/yii/blog2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/blognew/yii/blog2/index.php?r=Books/Crear
---
2014/12/03 02:19:13 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /srv/http/blognew/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /srv/http/blognew/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /srv/http/blognew/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /srv/http/blognew/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /srv/http/blognew/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /srv/http/blognew/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /srv/http/blognew/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /srv/http/blognew/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /srv/http/blognew/yii/framework/web/CWebApplication.php(282): CController->run('Crear')
#8 /srv/http/blognew/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('BookReviews/Cre...')
#9 /srv/http/blognew/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /srv/http/blognew/yii/blog2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/blognew/yii/blog2/index.php?r=BookReviews/Crear
---
2014/12/03 02:19:42 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /srv/http/blognew/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /srv/http/blognew/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /srv/http/blognew/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /srv/http/blognew/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /srv/http/blognew/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /srv/http/blognew/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /srv/http/blognew/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /srv/http/blognew/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /srv/http/blognew/yii/framework/web/CWebApplication.php(282): CController->run('Crear')
#8 /srv/http/blognew/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('BookReviews/Cre...')
#9 /srv/http/blognew/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /srv/http/blognew/yii/blog2/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/blognew/yii/blog2/index.php?r=BookReviews/Crear
---
